Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = false

  config.vm.define "ael-kadhS" do |server|
    server.vm.hostname = "ael-kadhS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
    end
    server.vm.provision "shell", inline:<<-SHELL
      sudo apt-get update
      sudo apt-get install -y curl net-tools
      # Install K3s with kubeconfig permissions
      curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --node-ip 192.168.56.110

      # changing the kubeconfig file to use the correct IP
      chmod 644 /etc/rancher/k3s/k3s.yaml
      sed -i 's/127\.0\.0\.1/192.168.56.110/g' /etc/rancher/k3s/k3s.yaml

      # Move the kubeconfig file to the shared folder
      cp /etc/rancher/k3s/k3s.yaml /vagrant/confs/k3s.yaml
      cp /var/lib/rancher/k3s/server/node-token /vagrant/confs/k3s-token

      # creating alias for kubectl
      echo "alias k=kubectl" >> .bashrc 
    SHELL
  end

  config.vm.define "ael-kadhSW" do |worker|
    worker.vm.hostname = "ael-kadhSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
    end
    worker.vm.provision "shell", inline:<<-SHELL
      sudo apt-get update
      sudo apt-get install -y curl net-tools

      # Get the K3s token from the shared folder
      K3S_TOKEN=$(cat /vagrant/confs/k3s-token)

      # Move the kubeconfig file to the correct location
      sudo mkdir -p /etc/rancher/k3s/
      sudo mv /vagrant/confs/k3s.yaml /etc/rancher/k3s/k3s.yaml
      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

      # Install K3s with kubeconfig permissions
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$K3S_TOKEN sh -s - --node-ip 192.168.56.111
      
      # Remove the token file from the shared folder for security reasons
      rm -rf /vagrant/confs/k3s-token

      # creating alias for kubectl
      echo "alias k=kubectl" >> .bashrc 
    SHELL
  end
end